from tkinter import *
import mysql.connector
root=Tk()
w,h=root.winfo_screenwidth(),root.winfo_screenheight()
root.geometry('%dx%d+0+0'%(w,h))
img=PhotoImage(file='.\\Bus_for_project.png')
Label(root,image=img).grid(row=0,column=0,padx=w//2.5,columnspan=10)
Label(root,text='Online Bus Booking System',font="Arial 24 bold", bg='light blue',fg='red').grid(row=1,column=0,columnspan=10)
Label(root,text='Bus Ticket',font="Arial 15 bold",fg='black').grid(row=2,column=0,columnspan=10,pady=h//20)
conn=mysql.connector.connect(host='localhost',user='root',password='Raghav@2001',database='project')
cur=conn.cursor()
cur.execute('select max(passenger_id) from passenger')
r=cur.fetchall()
cur.execute('select passenger_id,pname,gender,no_of_seats,mob_no,age,source,destination,bdate,tdate,fare,bus_id from passenger where passenger_id = {}'.format(r[0][0]))
res=cur.fetchall()
final=LabelFrame(root)
final.grid(row=8,column=4,columnspan=3)
Label(final, text='Passenger: {}'.format(res[0][1]),font='Arial 10 bold').grid(row=8,column=0)
Label(final, text='No of Seats: {}'.format(res[0][3]),font='Arial 10 bold').grid(row=9,column=0)
Label(final, text='Age: {}'.format(res[0][5]),font='Arial 10 bold').grid(row=10,column=0)
Label(final, text='Booking Ref.: {}'.format(res[0][0]),font='Arial 10 bold').grid(row=11,column=0)
Label(final, text='Travels on: {}'.format(res[0][9]),font='Arial 10 bold').grid(row=12,column=0)
Label(final, text='Gender: {}'.format(res[0][2]),font='Arial 10 bold').grid(row=8,column=1)
Label(final, text='Phone: {}'.format(res[0][4]),font='Arial 10 bold').grid(row=9,column=1)
Label(final, text='Fare Rs: {}'.format(int(res[0][10])*int(res[0][3])),font='Arial 10 bold').grid(row=10,column=1)
Label(final, text='Booked On: {}'.format(res[0][8]),font='Arial 10 bold').grid(row=11,column=1)
Label(final, text='Boarding Point: {}'.format(res[0][6]),font='Arial 10 bold').grid(row=12,column=1)
Label(final, text='Total amount Rs{} to be paid at the time of boarding he bus: '.format(int(res[0][10])*int(res[0][3])),fg='grey').grid(row=14,column=0,columnspan=2)
root.mainloop()

